"""Drafter agent - composes engagement content"""

import uuid
from typing import List, Optional
from datetime import datetime

from empirica.core.agents import spawn_epistemic_agent, EpistemicAgentConfig
from empirica_outreach.models import (
    ChannelProfile, Opportunity, ContentDraft, ContentType, DraftStatus
)
from empirica_outreach.storage import OutreachDatabase


class OutreachDrafter:
    """
    Composes engagement content adapted to channel audience.
    
    Uses spawn_epistemic_agent with outreach_drafter persona for composition.
    Outputs drafts with confidence scoring and epistemic markers.
    """
    
    def __init__(self, session_id: str):
        self.session_id = session_id
        self.db = OutreachDatabase()
    
    def draft_response(self, opportunity: Opportunity, 
                      channel: ChannelProfile,
                      variations: int = 1) -> List[ContentDraft]:
        """
        Draft response(s) to opportunity.
        
        Args:
            opportunity: Opportunity to respond to
            channel: Channel context
            variations: Number of draft variations to create
            
        Returns:
            List of draft variations
        """
        
        # Build task context
        task = self._build_draft_task(opportunity, channel)
        
        # Spawn epistemic agent with drafter persona
        config = EpistemicAgentConfig(
            session_id=self.session_id,
            task=task,
            persona_id="outreach_drafter",
            investigation_path=f"draft-{opportunity.id[:8]}",
            parent_context=f"""
Opportunity: {opportunity.type.value}
Source: {opportunity.source_content[:200]}
Relevance: {opportunity.relevance_score:.2f}
Channel: {channel.name}
Strategy: {channel.strategy.message_framing}
Tone: {channel.strategy.tone}
Audience: technical_level={channel.audience.technical_level:.2f}
"""
        )
        
        # For Phase 1, return agent result for external execution
        result = spawn_epistemic_agent(config, execute_fn=None)
        
        # Placeholder: would parse agent output for drafts
        # For Phase 1, create drafts directly
        drafts = self._create_drafts(opportunity, channel, variations)
        
        # Store drafts
        for draft in drafts:
            self.db.add_draft(draft)
        
        return drafts
    
    def _build_draft_task(self, opportunity: Opportunity, channel: ChannelProfile) -> str:
        """Build task description for drafter agent"""
        return f"""Draft response to this opportunity on {channel.name}.

**Opportunity Type:** {opportunity.type.value}
**Source Content:** {opportunity.source_content}
**Relevance:** {opportunity.relevance_score:.2f}

**Channel Strategy:**
- Message framing: {channel.strategy.message_framing}
- Entry point: {channel.strategy.entry_point}
- Tone: {channel.strategy.tone}

**Audience Profile:**
- Technical level: {channel.audience.technical_level:.2f}
- Pain points: {', '.join(channel.audience.pain_points)}
- Turn-offs: {', '.join(channel.audience.turn_offs)}

**Requirements:**
1. Match channel tone and framing
2. Address the pain point or question directly
3. Provide genuine value (no marketing fluff)
4. Include epistemic markers (acknowledge uncertainty where appropriate)
5. Suggest Empirica naturally, not as a sales pitch

**Output:**
- Draft body (200-500 words)
- Confidence score (0-1): How confident are you this will land well?
- Predicted engagement (0-1): Expected reaction
- Uncertainty flags: What are you unsure about?

Be honest about your confidence. Better to flag uncertainty than overclaim.
"""
    
    def _create_drafts(self, opportunity: Opportunity, 
                      channel: ChannelProfile, variations: int) -> List[ContentDraft]:
        """
        Create draft variations.
        
        Simplified implementation for Phase 1.
        Full implementation would parse agent output.
        """
        drafts = []
        
        # Base draft template (would be generated by agent)
        base_body = self._generate_draft_body(opportunity, channel)
        
        for i in range(variations):
            # Create variation
            draft = ContentDraft(
                id=str(uuid.uuid4()),
                opportunity_id=opportunity.id,
                channel_id=channel.id,
                content_type=ContentType.COMMENT,
                body=base_body,
                semantic_tags=["empirica", "epistemic-uncertainty", "context-management"],
                confidence_score=0.75 if opportunity.relevance_score > 0.8 else 0.65,
                predicted_engagement=opportunity.engagement_potential,
                uncertainty_flags=["tone match", "framing resonance"] if i == 0 else [],
                framing=channel.strategy.message_framing,
                tone=channel.strategy.tone,
                status=DraftStatus.PENDING_REVIEW  # Requires human approval
            )
            
            drafts.append(draft)
        
        return drafts
    
    def _generate_draft_body(self, opportunity: Opportunity, channel: ChannelProfile) -> str:
        """
        Generate draft body (simplified placeholder).
        
        Full implementation: Agent generates this with proper framing.
        """
        if opportunity.type.value == "pain_point_expressed":
            return f"""I've been dealing with this exact problem. What helped me was tracking what I know vs what I'm guessing explicitly.

[Insert context about Empirica here - epistemic self-awareness framework]

The key insight: if you're transparent about uncertainty, you can be systematic about learning. Not a magic fix, but makes progress measurable.

Happy to share more if useful."""
        
        elif opportunity.type.value == "question_we_can_answer":
            return f"""Good question. Here's what I've learned:

[Insert answer with epistemic markers]

This is based on [evidence]. I'm less certain about [uncertainty]. 

If you want to track this systematically, Empirica can help (it's what I use).

Let me know if you want specifics."""
        
        else:
            return f"""Interesting discussion. One thing I've found helpful:

[Insert relevant insight]

This connects to epistemic self-awareness - being explicit about what you know vs what you're guessing.

[Natural mention of Empirica if relevant]"""
    
    def get_drafts_for_review(self, channel_id: Optional[str] = None) -> List[ContentDraft]:
        """Get drafts pending human review"""
        return self.db.list_drafts(channel_id=channel_id, status="pending_review")
    
    def approve_draft(self, draft_id: str, feedback: Optional[str] = None):
        """Approve a draft for posting"""
        draft = self.db.get_draft(draft_id)
        if draft:
            draft.status = DraftStatus.APPROVED
            draft.human_feedback = feedback
            draft.reviewed_at = datetime.utcnow()
            self.db.update_draft(draft)
    
    def reject_draft(self, draft_id: str, feedback: str):
        """Reject a draft"""
        draft = self.db.get_draft(draft_id)
        if draft:
            draft.status = DraftStatus.REJECTED
            draft.human_feedback = feedback
            draft.reviewed_at = datetime.utcnow()
            self.db.update_draft(draft)
    
    def close(self):
        self.db.close()
    
    def __enter__(self):
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
